#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgnomekbd
Version  : 3.26.0
Release  : 5
URL      : https://github.com/GNOME/libgnomekbd/archive/3.26.0.tar.gz
Source0  : https://github.com/GNOME/libgnomekbd/archive/3.26.0.tar.gz
Summary  : GNOME keyboard shared library
Group    : Development/Tools
License  : LGPL-2.0
Requires: libgnomekbd-bin
Requires: libgnomekbd-data
Requires: libgnomekbd-lib
Requires: libgnomekbd-locales
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gdk-3.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libxklavier)

%description


%package bin
Summary: bin components for the libgnomekbd package.
Group: Binaries
Requires: libgnomekbd-data

%description bin
bin components for the libgnomekbd package.


%package data
Summary: data components for the libgnomekbd package.
Group: Data

%description data
data components for the libgnomekbd package.


%package dev
Summary: dev components for the libgnomekbd package.
Group: Development
Requires: libgnomekbd-lib
Requires: libgnomekbd-bin
Requires: libgnomekbd-data
Provides: libgnomekbd-devel

%description dev
dev components for the libgnomekbd package.


%package lib
Summary: lib components for the libgnomekbd package.
Group: Libraries
Requires: libgnomekbd-data

%description lib
lib components for the libgnomekbd package.


%package locales
Summary: locales components for the libgnomekbd package.
Group: Default

%description locales
locales components for the libgnomekbd package.


%prep
%setup -q -n libgnomekbd-3.26.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1505207229
%autogen --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1505207229
rm -rf %{buildroot}
%make_install
%find_lang libgnomekbd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gkbd-keyboard-display

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Gkbd-3.0.typelib
/usr/share/GConf/gsettings/libgnomekbd.convert
/usr/share/applications/gkbd-keyboard-display.desktop
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.libgnomekbd.desktop.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.libgnomekbd.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.libgnomekbd.keyboard.gschema.xml
/usr/share/libgnomekbd/icons/kbdled-caps-lock.svg
/usr/share/libgnomekbd/icons/kbdled-num-lock.svg
/usr/share/libgnomekbd/icons/kbdled-scroll-lock.svg
/usr/share/libgnomekbd/ui/show-layout.ui

%files dev
%defattr(-,root,root,-)
/usr/include/libgnomekbd/gkbd-configuration.h
/usr/include/libgnomekbd/gkbd-desktop-config.h
/usr/include/libgnomekbd/gkbd-indicator-config.h
/usr/include/libgnomekbd/gkbd-indicator.h
/usr/include/libgnomekbd/gkbd-keyboard-config.h
/usr/include/libgnomekbd/gkbd-keyboard-drawing.h
/usr/include/libgnomekbd/gkbd-status.h
/usr/include/libgnomekbd/gkbd-util.h
/usr/lib64/libgnomekbd.so
/usr/lib64/libgnomekbdui.so
/usr/lib64/pkgconfig/libgnomekbd.pc
/usr/lib64/pkgconfig/libgnomekbdui.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgnomekbd.so.8
/usr/lib64/libgnomekbd.so.8.0.0
/usr/lib64/libgnomekbdui.so.8
/usr/lib64/libgnomekbdui.so.8.0.0

%files locales -f libgnomekbd.lang
%defattr(-,root,root,-)

